site_name: 'Buddhist Digital Resource Center Asset Manager'
site_description: 'Project documentation and User Manual for Asset Manager'
site_author: 'Jim Katz'

theme: readthedocs

nav:
- Home: index.md
- Installation: user/AuditTool/Install-1.0.md
- Operation: user/AuditTool/AuditToolOperation-1.0.md
- Previous Versions:
   - 0.9 Installation: user/AuditTool/Install-0.9.md
   - 0.9 Operation: user/AuditTool/AuditToolOperation-0.9.md
#- Requirements:
#  - req/requirements.md
#  - req/tests.md
#- Building:
#    - Design: design/design.md
#- Resources:
#  - About: resources/about.md
#  - References: resources/resources.md

extra_css:
    - css/style.css
    - css/tooltip.css

extra:
  logo: images/bdrc-white.png
